version: "3"

services:

 web:
   ports:
     - "8000:80"
   build: ./docker/web
   container_name: web
   volumes:
     - ./src:/var/www/html

 db:
   image: mysql:8.0
   container_name: db
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: main_db
     MYSQL_USER: db_user
     MYSQL_PASSWORD: db_pass
     TZ: 'Asia/Tokyo'

   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 3306:3306